name: size_sdk_platform_interface
description: A common platform interface for the size_sdk plugin.
version: 0.0.1
homepage: https://your-homepage.com

environment:
  sdk: ^3.6.1 
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
